### ISSUE TITLE
PyPI out of date

### ISSUE THREAD

**Issue by rlaager** [cracklib/cracklib#65]
https://pypi.org/project/cracklib/ lists 2.9.3 as the most recent version.

I'm trying to install from pip, and 2.9.3 is the latest I can get.

**Comment by rlaager** [comment]
BTW, the reason I care about this is that I need a newer version to address #55. At this point, cracklib is simply uninstallable from pip for me (on Ubuntu 22.04). Obviously, there are other ways to install it, but this prevents me from (easily) installing it in a virtualenv.

**Comment by nneul** [comment]
@jandd I believe you're the owner of that package on pypi, can you update?

**Comment by jandd** [comment]
I just uploaded 2.9.6 (which is the version in current Debian and Ubuntu releases).

I tried to build and upload 2.9.11 too, but it seems like the Python support broke somewhere between 2.9.6 and 2.9.11:

`python3 setup.py test` now leads to

```
building '_cracklib' extension
x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I.. -I../lib -I/usr/include/python3.11 -c ./_cracklib.c -o build/temp.linux-x86_64-cpython-311/./_cracklib.o
./_cracklib.c: In function ‘_cracklib_FascistCheck’:
./_cracklib.c:138:33: error: ‘LOCALEDIR’ undeclared (first use in this function)
  138 |         bindtextdomain(PACKAGE, LOCALEDIR);
      |                                 ^~~~~~~~~
./_cracklib.c:138:33: note: each undeclared identifier is reported only once for each function it appears in
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
```

`LOCALEDIR` is defined in src/python/Makefile.am, but not in the Python build.

**Comment by jandd** [comment]
This is broken since 2e0f854bada720ff4fbd13aed4f87087d466274d

@nekopsykose did you test the Python binding after this change? How do you build the Python extension?

**Comment by nekopsykose** [comment]
via autotools, i.e. `./configure` and `make`. that still works, because autotools defines LOCALEDIR in AM_CPPFLAGS, which get passed to the non-setuptools build. i did not test the setup.py, apologies for that!

for setuptools, you would have to add some form of flags into the setup.py.in, but i'm not quite sure how to pass a localedir in the same way as autotools does, or how the arguments expand there (into the final generated setup.py)

**Comment by nekopsykose** [comment]
@thesamesam do you remember how this expansion works, to put AM_ flags into a setup.py.in from autotools?

**Comment by jandd** [comment]
The issue I see with this is that the source artifacts on PyPI only contain the code that is packaged by python3 setup.py sdist. This needs to be independent of the environment. A user that installs the cracklib binding via pip will expect that it works with whatever cracklib library is on his/her system. I think putting environment specific paths like `LOCALEDIR` inside the `python/_cracklib.c` is a bad idea in this context.

Would it be an option to document that a Python application that uses the cracklib binding, must call `bindtextdomain()` to make sure that the locale files will be found?

**Comment by nekopsykose** [comment]
not sure. afaik i've seen most(?) python libraries call bindtext themselves, albeit with some canned value i have forgotten.

i'm indifferent to it- if it's what helps you make a pypi release, go for it :) i wouldn't know what is best in this specific scenario.

**Comment by nneul** [comment]
What about adding an internal library function in cracklib that returns the path that it was compiled with, which should match the host OS?

**Comment by jandd** [comment]
@nneul I think it is a good idea. We should conditionally include the bindtextdomain in python/_cracklib.c (gated by an `#ifdef`) to not break building of the binding when a user has an older cracklib version on his system (which will be the default case until all distributions ship a version that will include the new internal function).

Rough draft:

* the main library header file (cracklib.h) defines `LOCALEDIR` and the signature for _get_locale_dir
* a helper function `_get_locale_dir` is included in the main library
* the Python binding (python/_cracklib.c) uses
  ```c
  #ifdef LOCALEDIR
  bindtextdomain(PACKAGE, _get_locale_dir());
  #endif
  ```

**Comment by rlaager** [comment]
Is that a valid solution? I'd really love to be able to install cracklib in a virtualenv.
